server:
  port: 9003

spring:
  application:
    name: zuul
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mofancoder/springcloud-config.git
          search-paths: zuul-config
        default-label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/

zuul:
  prefix: /a
  routes:
    client:
      path: /client/**
      serviceId: client
  ##添加API接口版本号

